# Install Windows host metrics -> Coralogix
# Run in PowerShell as Administrator:
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#   .\install-windows.ps1

#Requires -RunAsAdministrator

$ErrorActionPreference = "Stop"
$VERSION = "0.112.0"
$SERVICE_NAME = "CoralogixOtelCollector"
$INSTALL_DIR = "$PSScriptRoot"
$BINARY = "$INSTALL_DIR\otelcol-contrib.exe"
$LOCAL_CONFIG = "$INSTALL_DIR\config-windows-local.yaml"
$LOG_FILE = "$INSTALL_DIR\collector.log"

Write-Host ""
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host "  Windows Host Metrics -> Coralogix  Installer" -ForegroundColor Cyan
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host ""

# ── 1. Get machine name ───────────────────────────────
$defaultName = $env:COMPUTERNAME.ToLower() -replace '[^a-z0-9-]', '-'
Write-Host "Enter a name for this machine (used in Coralogix as application name)."
Write-Host "Press Enter to use the default: [$defaultName]"
$machineInput = Read-Host "Machine name"
if ([string]::IsNullOrWhiteSpace($machineInput)) {
    $CX_APP_NAME = $defaultName
} else {
    $CX_APP_NAME = $machineInput.ToLower() -replace '[^a-z0-9-]', '-'
}
Write-Host "Using application name: $CX_APP_NAME" -ForegroundColor Green

# ── 2. Get Coralogix private key ──────────────────────
if ($env:CORALOGIX_PRIVATE_KEY) {
    $CX_KEY = $env:CORALOGIX_PRIVATE_KEY
    Write-Host "Using CORALOGIX_PRIVATE_KEY from environment." -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "Enter your Coralogix Send-Your-Data API key (starts with cxtp_):"
    $secureKey = Read-Host -AsSecureString
    $CX_KEY = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureKey)
    )
    if ([string]::IsNullOrWhiteSpace($CX_KEY)) {
        Write-Error "API key is required."
        exit 1
    }
}

# ── 3. Download binary if missing ────────────────────
if (-not (Test-Path $BINARY)) {
    Write-Host ""
    Write-Host "Downloading otelcol-contrib v$VERSION for Windows..."
    $tarUrl = "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v$VERSION/otelcol-contrib_${VERSION}_windows_amd64.tar.gz"
    $tarPath = "$INSTALL_DIR\otelcol-contrib.tar.gz"
    Invoke-WebRequest -Uri $tarUrl -OutFile $tarPath -UseBasicParsing
    Write-Host "Extracting..."
    & tar -xzf $tarPath -C $INSTALL_DIR otelcol-contrib.exe
    Remove-Item $tarPath
    Write-Host "Binary ready." -ForegroundColor Green
} else {
    Write-Host "otelcol-contrib binary already present." -ForegroundColor Green
}

# ── 4. Generate resolved config (values baked in, no env vars) ───
Write-Host "Generating config..."
$logFilePath = $LOG_FILE -replace '\\', '\\'
@"
# OpenTelemetry Collector - Windows to Coralogix (auto-generated by install-windows.ps1)
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      disk: {}
      process:
        mute_process_all_errors: true
      memory: {}
      network: {}
      filesystem: {}
      paging: {}

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  resource:
    attributes:
      - key: deployment.environment.name
        value: "local-windows"
        action: upsert

exporters:
  coralogix:
    domain: "eu2.coralogix.com"
    private_key: "$CX_KEY"
    application_name: "$CX_APP_NAME"
    subsystem_name: "host-metrics"
    timeout: 30s
  debug:
    verbosity: basic
    sampling_initial: 2
    sampling_thereafter: 10

service:
  telemetry:
    logs:
      level: warn
      output_paths: ["$logFilePath"]
      error_output_paths: ["$logFilePath"]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resource, batch]
      exporters: [coralogix, debug]
"@ | Set-Content $LOCAL_CONFIG -Encoding UTF8
Write-Host "Config written to $LOCAL_CONFIG" -ForegroundColor Green

# ── 5. Stop & remove existing service if present ─────
if (Get-Service -Name $SERVICE_NAME -ErrorAction SilentlyContinue) {
    Write-Host "Stopping existing service..."
    Stop-Service -Name $SERVICE_NAME -Force -ErrorAction SilentlyContinue
    sc.exe delete $SERVICE_NAME | Out-Null
    Start-Sleep -Seconds 2
}

# ── 6. Register the binary directly as a Windows service ─────
Write-Host "Creating Windows Service..."
$binPath = "`"$BINARY`" --config `"$LOCAL_CONFIG`""
sc.exe create $SERVICE_NAME binPath= $binPath start= auto DisplayName= "Coralogix OTel Collector" | Out-Null
sc.exe description $SERVICE_NAME "Sends host metrics to Coralogix via OpenTelemetry" | Out-Null

# ── 7. Start the service ──────────────────────────────
Write-Host "Starting service..."
Start-Service -Name $SERVICE_NAME
Start-Sleep -Seconds 8

$svc = Get-Service -Name $SERVICE_NAME
if ($svc.Status -eq "Running") {
    Write-Host ""
    Write-Host "=================================================" -ForegroundColor Green
    Write-Host "  Installation complete!" -ForegroundColor Green
    Write-Host "=================================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Metrics will appear in Coralogix within ~2 min"
    Write-Host "  Application name : $CX_APP_NAME"
    Write-Host "  Subsystem name   : host-metrics"
    Write-Host ""
    Write-Host "  Useful commands:"
    Write-Host "    Status:    Get-Service $SERVICE_NAME"
    Write-Host "    Logs:      Get-Content '$LOG_FILE' -Tail 30 -Wait"
    Write-Host "    Stop:      Stop-Service $SERVICE_NAME"
    Write-Host "    Uninstall: .\uninstall-windows.ps1"
    Write-Host ""
} else {
    Write-Warning "Service status: $($svc.Status). Check logs:"
    Write-Warning "  Get-Content '$LOG_FILE' -Tail 30"
    exit 1
}
